### ISSUE TITLE
Can't execute nfetch at try to compile it manually

### ISSUE THREAD

**Issue by AlphaTechnolog** [Infinitybeond1/nfetch-src#3]
# Can't execute nfetch at try to compile it manually

So, i'm in void, and the prebuilt binaries don't work for me, it shows me that i have another glibc version in my system, and is right, so i tried to compile it manually using the next commands:

```sh
git clone https://github.com/Infinitybeond1/nfetch-src nfetch
cd nfetch
nimble build
```

and tried to execute like this:

```sh
./nfetch
```

But it throws me some errors

![Screenshot from 2022-05-27 06-22-43](https://user-images.githubusercontent.com/54639968/170682184-ddd09d7f-4ee8-474c-9973-19db074f1b4d.png)

idk what's happening, i think i miss some configurations files in `/usr/share/doc`, but really i don't know how to get them, so, i opened this issue.

# Idk if the next info is useful, but i'll put it in this lmao

I don't know if the next information is useful, i installed `nimble` using the pkg `nim` in void linux:

```sh
sudo xbps-install -y nim
```

and i tried to update too the system to get a more latest glibc, and make work prebuilt binaries, but no luck, because i use

```sh
sudo xbps-install -Syu
```

and it shows me that i don't have updates xD

**Comment by Magniquick** [comment]
https://discord.com/channels/635612648934735892/635625758412505093/979398704584884224

**Comment by AlphaTechnolog** [comment]
> https://discord.com/channels/635612648934735892/635625758412505093/979398704584884224

worked, thanks!

**Comment by FabioLolix** [comment]
And the solution is?

Edit:

`install -D config.ini -t "${pkgdir}/usr/share/doc/nfetch"`
